/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sipetor.view;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sipetor.controller.ControllerDetailService;
import sipetor.controller.ControllerHeadService;
import sipetor.controller.ControllerKaryawan;
import sipetor.controller.ControllerPelanggan;
import sipetor.controller.ControllerSparepart;
import sipetor.model.DetailService;
import sipetor.model.HeadService;
import sipetor.model.Karyawan;
import sipetor.model.Pelanggan;
import sipetor.model.Sparepart;

/**
 *
 * @author takahashidandy
 */
public class FormTrans extends javax.swing.JFrame {
    ControllerKaryawan controllerKaryawan = new ControllerKaryawan();
    ControllerPelanggan controllerPelanggan = new ControllerPelanggan();
    ControllerSparepart controllerSparepart = new ControllerSparepart();
    ControllerDetailService controllerDetailService = new ControllerDetailService();
    ControllerHeadService controllerHeadService = new ControllerHeadService();
    List<DetailService> collection = new ArrayList<>();
    int totalpembelian = 0;
    float ppn = 0;
    float grandtotal =0;
    /**
     * Creates new form FormTrans
     */
    public FormTrans() {
        initComponents();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchData = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        txtPencarian = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblIdTransaksi = new javax.swing.JLabel();
        lblTnkb = new javax.swing.JLabel();
        lblIdKaryawan = new javax.swing.JLabel();
        lblNamaPelanggan = new javax.swing.JLabel();
        lblNamaMontir = new javax.swing.JLabel();
        btnPelanggan = new javax.swing.JButton();
        btnMontir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtPembayaran = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblTotalPembelian = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPpn = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblGrandTot = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblKembalian = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();
        btnTambahDetail = new javax.swing.JButton();
        btnDeleteDetail = new javax.swing.JButton();

        searchData.setAlwaysOnTop(true);
        searchData.setMinimumSize(new java.awt.Dimension(600, 600));

        jLabel8.setText("Nama");

        txtPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPencarianKeyTyped(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil Pencarian"));

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblResultMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(tblResult);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout searchDataLayout = new javax.swing.GroupLayout(searchData.getContentPane());
        searchData.getContentPane().setLayout(searchDataLayout);
        searchDataLayout.setHorizontalGroup(
            searchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtPencarian, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCari)
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchDataLayout.setVerticalGroup(
            searchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Head Transaksi"));

        jLabel1.setText("Tanggal");

        jLabel2.setText("ID Transaksi");

        jLabel3.setText("TNKB");

        jLabel4.setText("Montir");

        lblTanggal.setText("tanggal");

        lblIdTransaksi.setText("transaksi");

        lblTnkb.setText("tnkb");

        lblIdKaryawan.setText("id_karyawan");

        lblNamaPelanggan.setText("nama_pemilik");

        lblNamaMontir.setText("nama_montir");

        btnPelanggan.setText("Search Pelanggan");
        btnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelangganActionPerformed(evt);
            }
        });

        btnMontir.setText("Search Montir");
        btnMontir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMontirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTanggal)
                            .addComponent(lblIdTransaksi)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdKaryawan)
                                    .addComponent(lblTnkb))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNamaPelanggan)
                                    .addComponent(lblNamaMontir))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPelanggan)
                                    .addComponent(btnMontir)))))
                    .addComponent(jLabel4))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTanggal))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblIdTransaksi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTnkb)
                    .addComponent(btnPelanggan)
                    .addComponent(lblNamaPelanggan))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblIdKaryawan)
                    .addComponent(btnMontir)
                    .addComponent(lblNamaMontir)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Pembayaran"));

        txtPembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPembayaranKeyTyped(evt);
            }
        });

        jLabel5.setText("Total Pembelian");

        lblTotalPembelian.setText("0");

        jLabel7.setText("PPN 10%");

        lblPpn.setText("0");

        jLabel9.setText("Grand Total");

        lblGrandTot.setText("0");

        jLabel11.setText("Jumlah Bayar");

        jLabel6.setText("Kembali");

        lblKembalian.setText("0");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalPembelian)
                    .addComponent(lblKembalian)
                    .addComponent(lblPpn)
                    .addComponent(lblGrandTot)
                    .addComponent(txtPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTotalPembelian)
                    .addComponent(btnSimpan))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblPpn)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblGrandTot)
                    .addComponent(btnClose))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblKembalian))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Transaksi"));

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDetail);

        btnTambahDetail.setText("+");
        btnTambahDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDetailActionPerformed(evt);
            }
        });

        btnDeleteDetail.setText("-");
        btnDeleteDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTambahDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteDetail)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahDetail)
                    .addComponent(btnDeleteDetail)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
        setTablePelanggan(controllerPelanggan.getAllData());
        searchData.requestFocusInWindow();
        searchData.setVisible(true);
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnMontirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMontirActionPerformed
        setTableKaryawan(controllerKaryawan.getAllData());
        searchData.setVisible(true);
    }//GEN-LAST:event_btnMontirActionPerformed

    private void tblResultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMousePressed
        if(evt.getClickCount() == 2){
            String colName = tblResult.getColumnModel().getColumn(0).getHeaderValue().toString();
            int idxrow = tblResult.getSelectedRow();
            if(colName.equals("NIK")){
                lblIdKaryawan.setText(tblResult.getModel().getValueAt(idxrow, 0).toString());
                lblNamaMontir.setText(tblResult.getModel().getValueAt(idxrow, 2).toString());
            } else if(colName.equals("Id Pelanggan")){
                lblTnkb.setText(tblResult.getModel().getValueAt(idxrow, 0).toString());
                lblNamaPelanggan.setText(tblResult.getModel().getValueAt(idxrow, 1).toString());
            } else{
                int id_reg = 0;
                String id_transaksi = lblIdTransaksi.getText();
                String id_sparepart = tblResult.getModel().getValueAt(idxrow, 0).toString();
                int jumlah_beli = 1;
                int stotal_beli = Integer.parseInt(tblResult.getModel().getValueAt(idxrow,2).toString());
                int total_beli = jumlah_beli * stotal_beli;
                
                DetailService data = new DetailService(id_reg, id_transaksi, 
                        id_sparepart, jumlah_beli, 
                        total_beli);
                totalpembelian += total_beli;
                lblTotalPembelian.setText(totalpembelian+"");
                ppn = totalpembelian * 0.1f;
                grandtotal = totalpembelian + ppn;
                lblPpn.setText(ppn + "");
                lblGrandTot.setText(grandtotal + "");
                collection.add(data);
            }
            searchData.dispose();
            setTableDetail(collection);
        }
    }//GEN-LAST:event_tblResultMousePressed

    private void btnTambahDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDetailActionPerformed
        setTableSparepart(controllerSparepart.getallData());
        searchData.setVisible(true);
    }//GEN-LAST:event_btnTambahDetailActionPerformed

    private void btnDeleteDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDetailActionPerformed
        if(collection.size() >= 0){
            totalpembelian -= collection.get(0).getTotal_beli();
            lblTotalPembelian.setText(totalpembelian+"");
            ppn = totalpembelian * 0.1f;
            grandtotal = totalpembelian + ppn;
            lblPpn.setText(ppn + "");
            lblGrandTot.setText(grandtotal + "");
            collection.remove(0);
            setTableDetail(collection);
        }
    }//GEN-LAST:event_btnDeleteDetailActionPerformed

    private void txtPembayaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPembayaranKeyTyped
        if(evt.getKeyCode() == 0){
           if(!txtPembayaran.getText().equals("")){
                int money = Integer.parseInt(txtPembayaran.getText());
                float change = money - grandtotal;
                lblKembalian.setText((change < 0 ? 0+"" : change+""));
            }
        }
    }//GEN-LAST:event_txtPembayaranKeyTyped

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        HeadService head = new HeadService(
                lblIdTransaksi.getText(), lblIdKaryawan.getText(), 
                lblTnkb.getText(), lblTanggal.getText(), 
                Integer.parseInt(txtPembayaran.getText()),
                Integer.parseInt(lblTotalPembelian.getText())
        );
        controllerHeadService.insertHeadService(head);
        
        for(DetailService data : collection){
            DetailService detail = new DetailService(
                    controllerDetailService.generateID(),data.getId_transaksi(),
                    data.getId_sparepart(),data.getJumlah_beli(),
                    data.getTotal_beli()
            );
            controllerDetailService.insertDetailService(detail);
        }
        setClear();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        setClear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtPencarianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPencarianKeyTyped
        String colName = tblResult.getColumnModel().getColumn(0).getHeaderValue().toString();
        if(colName.equals("NIK")){
            setTableKaryawan(controllerKaryawan.getAllKaryawanByName(txtPencarian.getText()));
        } else if(colName.equals("Id Pelanggan")){
            setTablePelanggan(controllerPelanggan.getAllPelangganByName(txtPencarian.getText()));
        } else{
            setTableSparepart(controllerSparepart.getAllSparepartByName(txtPencarian.getText()));
        }
    }//GEN-LAST:event_txtPencarianKeyTyped
    
    public void initData(){
        Calendar c = Calendar.getInstance();
        String date = c.get(Calendar.YEAR) +"/"+ (c.get(Calendar.MONTH)+1) +"/"+ c.get(Calendar.DATE);
        lblTanggal.setText(date);
        lblIdTransaksi.setText(controllerHeadService.generateID()+"");
        setTableDetail(collection);
    }
    
    private void setTablePelanggan(List<Pelanggan> listPelanggan) {
       if (listPelanggan==null){
           JOptionPane.showMessageDialog(this, "Data produk gagal diambil dari database","DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
       }else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
               new String[] {
                   "Id Pelanggan",
                   "Nama Pelanggan",
                   "Alamat Pelanggan"
               }
           );

           for (Pelanggan p : listPelanggan) {
               Object[] o = new Object[3];
               o[0] = p.getTnkb();
               o[1] = p.getNama_Pelanggan();
               o[2] = p.getAlamat_Pelanggan();
               tableModel.addRow(o);
           }
           tblResult.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblResult.setModel(tableModel);
       }
    }
    
    private void setTableKaryawan(List<Karyawan> listKaryawan) {
       if (listKaryawan==null){
           JOptionPane.showMessageDialog(this, "Data produk gagal diambil dari database","DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
       }else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
               new String[] {
                   "NIK",
                   "Golongan",
                   "Nama Karyawan",
                   "Alamat Karyawan",
                   "Email Karyawan"
               }
           );

           for (Karyawan g : listKaryawan) {
               Object[] o = new Object[5];
               o[0] = g.getNik();
               o[1] = g.getId_golongan();
               o[2] = g.getNama_karyawan();
               o[3] = g.getAlamat_karyawan();
               o[4] = g.getEmail_karyawan();
               tableModel.addRow(o);
           }
           tblResult.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblResult.setModel(tableModel);
       }
    }
    
    private void setTableSparepart(List<Sparepart> listSparepart) {
       if (listSparepart==null){
           JOptionPane.showMessageDialog(this, "Data gagal diambil dari database","DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
       }else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
               new String[] {
                   "Id Sparepart",
                   "Nama Sparepart",
                   "Harga Sparepart",
                   "Stock Sparepart"
               }
           );

           for (Sparepart s : listSparepart) {
               Object[] o = new Object[4];
               o[0] = s.getId_sparepart();
               o[1] = s.getNama_sparepart();
               o[2] = s.getHarga_sparepart();
               o[3] = s.getStock_sparepart();
               tableModel.addRow(o);
           }
           tblResult.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblResult.setModel(tableModel);
       }
    }
    
    private void setTableDetail(List<DetailService> listDetailService){
        if (listDetailService==null){
           JOptionPane.showMessageDialog(this, "Data produk gagal diambil dari database","DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
       }else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
               new String[] {
                   "Id Registrasi",
                   "Id Transaksi",
                   "Id sparepart",
                   "Jumlah Beli",
                   "Total Beli"
               }
           );
           
           for (DetailService g : listDetailService) {
               Object[] o = new Object[5];
               
               o[0] = controllerDetailService.generateID();
               o[1] = g.getId_transaksi();
               o[2] = g.getId_sparepart();
               o[3] = g.getJumlah_beli();
               o[4] = g.getTotal_beli();
               tableModel.addRow(o);
           }
           tblDetail.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblDetail.setModel(tableModel);
       }
    } 
    
    private void setClear(){
        //membersihkan data head transaksi
        Calendar c = Calendar.getInstance();
        String date = c.get(Calendar.YEAR) +"/"+ c.get(Calendar.MONTH) +"/"+ c.get(Calendar.DATE);
        lblTanggal.setText(date);
        lblIdTransaksi.setText(controllerHeadService.generateID()+"");
        lblIdKaryawan.setText("id_karyawan");
        lblNamaMontir.setText("id_montir");
        lblTnkb.setText("tnkb_pelanggan");
        lblNamaPelanggan.setText("nama_pelanggan");
        
        //membersihkan data detail transaksi
        collection.clear();
        setTableDetail(collection);
        
       
        //membersihkan data perhitungan
        lblTotalPembelian.setText("0");
        lblPpn.setText("0");
        lblGrandTot.setText("0");
        txtPembayaran.setText("0");
        lblKembalian.setText("0");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTrans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDeleteDetail;
    private javax.swing.JButton btnMontir;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblGrandTot;
    private javax.swing.JLabel lblIdKaryawan;
    private javax.swing.JLabel lblIdTransaksi;
    private javax.swing.JLabel lblKembalian;
    private javax.swing.JLabel lblNamaMontir;
    private javax.swing.JLabel lblNamaPelanggan;
    private javax.swing.JLabel lblPpn;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTnkb;
    private javax.swing.JLabel lblTotalPembelian;
    private javax.swing.JDialog searchData;
    private javax.swing.JTable tblDetail;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextField txtPembayaran;
    private javax.swing.JTextField txtPencarian;
    // End of variables declaration//GEN-END:variables
}
