/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sipetor.view;

import javax.swing.JOptionPane;
import sipetor.report.GenerateReport;

/**
 *
 * @author User
 */
public class FormMainMenu extends javax.swing.JFrame {
    
    
    /**
     * Creates new form FotmMainMenu
     */
    public FormMainMenu() {
        initComponents();
    }

    FormMainMenu(String Username) {
        initComponents();
        lblGuest.setText(Username);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        lblGuest = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnquit = new javax.swing.JMenuItem();
        mnLogOut = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnGolongan = new javax.swing.JMenuItem();
        mnKaryawan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnSparepart = new javax.swing.JMenuItem();
        mnPelanggan = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnTransaksi = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        btnreport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SIPETOR MAIN MENU");

        jToolBar1.setRollover(true);

        jLabel1.setText("Username : ");
        jToolBar1.add(jLabel1);

        lblGuest.setText("Guest");
        jToolBar1.add(lblGuest);

        jMenu1.setText("File");

        mnquit.setText("Quit");
        mnquit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnquitActionPerformed(evt);
            }
        });
        jMenu1.add(mnquit);

        mnLogOut.setText("LogOut");
        mnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(mnLogOut);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Admin Data");

        mnGolongan.setText("Golongan");
        mnGolongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGolonganActionPerformed(evt);
            }
        });
        jMenu2.add(mnGolongan);

        mnKaryawan.setText("Karyawan");
        mnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKaryawanActionPerformed(evt);
            }
        });
        jMenu2.add(mnKaryawan);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Master Data");

        mnSparepart.setText("Sparepart");
        mnSparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSparepartActionPerformed(evt);
            }
        });
        jMenu3.add(mnSparepart);

        mnPelanggan.setText("Pelanggan");
        mnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPelangganActionPerformed(evt);
            }
        });
        jMenu3.add(mnPelanggan);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Transaksi");

        mnTransaksi.setText("Transaksi");
        mnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransaksiActionPerformed(evt);
            }
        });
        jMenu4.add(mnTransaksi);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Report");

        btnreport.setText("Report");
        btnreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportActionPerformed(evt);
            }
        });
        jMenu5.add(btnreport);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 279, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnGolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGolonganActionPerformed
       new FormMainGolongan(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_mnGolonganActionPerformed

    private void mnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKaryawanActionPerformed
       new FormMainKaryawan(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_mnKaryawanActionPerformed

    private void mnquitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnquitActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "Apakah Anda Yakin Akan Log Out?","Confrim Dialog",JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            this.dispose();
           System.exit(0);
        }
    }//GEN-LAST:event_mnquitActionPerformed

    private void mnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogOutActionPerformed
        this.dispose();
        new FormMainLogin(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_mnLogOutActionPerformed

    private void mnSparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSparepartActionPerformed
        new FormMainSparepart(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_mnSparepartActionPerformed

    private void mnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPelangganActionPerformed
        new FormMainPelanggan(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_mnPelangganActionPerformed

    private void mnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransaksiActionPerformed
        new FormTrans().setVisible(true);
    }//GEN-LAST:event_mnTransaksiActionPerformed

    private void btnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportActionPerformed
        GenerateReport g = new GenerateReport();
        g.GenerateReportTransaksi();
    }//GEN-LAST:event_btnreportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnreport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblGuest;
    private javax.swing.JMenuItem mnGolongan;
    private javax.swing.JMenuItem mnKaryawan;
    private javax.swing.JMenuItem mnLogOut;
    private javax.swing.JMenuItem mnPelanggan;
    private javax.swing.JMenuItem mnSparepart;
    private javax.swing.JMenuItem mnTransaksi;
    private javax.swing.JMenuItem mnquit;
    // End of variables declaration//GEN-END:variables
}
